import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@madrasah/ui/globals.css'
const inter = Inter({ subsets: ['latin'] })

import AppLayout from '~/components/layout/app-layout'
import { ClientProviders } from '~/components/providers/client-providers'
import { hasLocale, NextIntlClientProvider } from 'next-intl'
import { notFound } from 'next/navigation'
import { setRequestLocale } from 'next-intl/server'
import { routing } from '~/lib/i18n/routing'

export const metadata: Metadata = {
  title: 'Nizam',
  description: 'Generated by create next app',
}

export default async function LocaleLayout({
  children,
  params,
}: { children: React.ReactNode, params: Promise<{ locale: string }> }) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  setRequestLocale(locale)

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextIntlClientProvider>
          <ClientProviders>
            <AppLayout>{children}</AppLayout>
          </ClientProviders>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
