-- Reverses migrations/0022_kosk_listed_by_default.sql (MDRS-122). The app never
-- runs this: drizzle's migrator only moves forward. To roll back by hand, run
-- it, then delete 0022's row from "drizzle"."__drizzle_migrations" so that the
-- next boot applies it again. Only the column default moves back. The
-- forward migration also listed every existing köşk (owner decision,
-- 2026-10-02), and that is NOT undone here: which köşks were unlisted before
-- 0022 is not recorded, and nearly all of them were unlisted only because the
-- old default said so. Every köşk stays listed after the rollback; unlist one
-- through nizam's köşk form or a PATCH.
-- Pinned by test/e2e/kosk-listed-by-default-migration.e2e.spec.ts.
ALTER TABLE "kosks" ALTER COLUMN "is_private" SET DEFAULT true;
