#!/usr/bin/env node
//
// Distribute the root environment file into the per-app files the frameworks
// already expect (MDRS-25).
//
// WHY
// Six apps carried six hand-maintained `.env` files with 32 distinct keys, 24
// of them repeated in two or more files. Every repeat was a chance to drift,
// and the drift was real: `apps/nazir/.env` pointed at the remote dev API
// while nizam and tedris pointed at localhost, `apps/tedris/.env.example` named
// port 4001 for an API that listens on 3001, and one Keycloak client secret had
// been pasted into two other apps as their NextAuth signing secret.
//
// The frameworks cannot be asked to read a different file: NextAuth reads
// NEXTAUTH_URL, Nest reads PORT, Next reads NODE_ENV — all by their canonical
// names, from `apps/<app>/.env`. So the root file stays the only thing a human
// edits and this script flattens it back into what the frameworks expect.
//
// KEY CONVENTION
//   KEY=value            shared — written to every app
//   WEB__KEY=value       written to the four Next.js apps, overriding shared
//   API__KEY=value       written to the two NestJS apps, overriding shared
//   NIZAM__KEY=value     written to apps/nizam only, overriding both
//
// The double underscore cannot collide with a real prefix such as NEXT_PUBLIC_.
// Precedence is shared < group < app; the prefix is stripped on the way out, so
// `NIZAM__NEXTAUTH_URL` lands in `apps/nizam/.env` as `NEXTAUTH_URL`.
//
// MDRS-25 specifies only the shared and per-app rules. The two group prefixes
// are an addition, and they earn their place: without them every backend-only
// key (DB_PASSWORD, DB_USERNAME, the OTEL exporter settings) would either be
// broadcast into the four web apps — spraying database credentials into env
// files that have no database — or be written twice, once per API, which is the
// duplication this whole exercise exists to remove.
//
// ROOT_ONLY is the one thing the prefix scheme cannot express. docker-compose
// reads the root `.env` itself, by the canonical key name, so those keys cannot
// carry a prefix and must not be broadcast either.
//
// USAGE
//   node tools/env/sync-env.mjs             sync .env.example and, if present, .env
//   node tools/env/sync-env.mjs --examples  sync only the committed .env.example files
//   node tools/env/sync-env.mjs --check     write nothing; exit 1 if anything is stale
//   node tools/env/sync-env.mjs --collect   print a root .env assembled from the
//                                           existing per-app files (one-time migration)
//
// FIRST RUN ON AN EXISTING MACHINE
// `pnpm env:sync` replaces apps/<app>/.env with whatever the root .env says, so
// build the root file from what you already have before running it:
//
//   pnpm env:collect > .env      # review it, then
//   pnpm env:sync
//
// Anything it overwrites that this script did not write is copied to `.env.bak`
// first, so a first run cannot lose a secret that exists nowhere else.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

// The six apps that consume an env file. `keycloak-theme` is deliberately absent
// — it ships no .env and reads its configuration from the Keycloak server.
const WEB_APPS = ["landing", "nazir", "nizam", "tedris"];
const API_APPS = ["tedrisat", "teskilat"];
const APPS = [...WEB_APPS, ...API_APPS];

const GROUPS = { WEB: WEB_APPS, API: API_APPS };

// Consumed from the root file by docker-compose under these exact names, so
// they can neither be prefixed nor pushed down into the apps.
const ROOT_ONLY = new Set([
  "TEDRISAT_PORT",
  "TESKILAT_PORT",
  "MEDARIS_POSTGRES_USER",
  "MEDARIS_POSTGRES_PASSWORD",
  "MEDARIS_POSTGRES_DB",
  "MEDARIS_POSTGRES_PORT",
]);

const MARKER = "GENERATED by tools/env/sync-env.mjs";

const header = (source) =>
  [
    `# ${MARKER} — do not edit.`,
    `#`,
    `# Every value here comes from ${source} at the repository root. Edit that`,
    `# file and run \`pnpm env:sync\`; anything changed here is lost on the next`,
    `# run, and CI fails when this file and its source disagree.`,
    ``,
    ``,
  ].join("\n");

/**
 * Parse KEY=VALUE lines. Comments and blank lines are dropped rather than
 * carried across: a comment written next to a shared key would be duplicated
 * into six files, where it reads as six independent statements that then drift
 * apart on their own. Explanation belongs in the root file only.
 */
function parseEnv(text) {
  const entries = [];
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (line === "" || line.startsWith("#")) continue;
    const eq = line.indexOf("=");
    if (eq === -1) continue;

    let value = line.slice(eq + 1);
    // dotenv drops an unquoted trailing comment, so a value written as
    // `localhost:4317 # collector` already reaches the app as `localhost:4317`.
    // Strip it here too, or the generated file would carry a comment that only
    // some parsers ignore.
    if (!/^\s*["']/.test(value)) value = value.replace(/\s+#.*$/, "");

    entries.push({ key: line.slice(0, eq).trim(), value: value.trim() });
  }
  return entries;
}

/** Split `NIZAM__NEXTAUTH_URL` into its target and its canonical key name. */
function classify(key) {
  const split = key.indexOf("__");
  if (split === -1) {
    return ROOT_ONLY.has(key)
      ? { scope: "root", targets: [], key }
      : { scope: "shared", targets: APPS, key };
  }

  const prefix = key.slice(0, split);
  const canonical = key.slice(split + 2);

  if (canonical === "")
    throw new Error(`"${key}" has a prefix but no key after it.`);
  if (GROUPS[prefix])
    return { scope: "group", targets: GROUPS[prefix], key: canonical };

  const app = prefix.toLowerCase();
  if (APPS.includes(app))
    return { scope: "app", targets: [app], key: canonical };

  throw new Error(
    `"${key}" names "${prefix}", which is not an app or a group. ` +
      `Expected one of: ${[...Object.keys(GROUPS), ...APPS.map((a) => a.toUpperCase())].join(", ")}.`
  );
}

/**
 * Flatten the source into one map per app. Order of application is the whole
 * point: shared first, then the group, then the app, so the narrowest
 * declaration wins regardless of where it sits in the file.
 */
function distribute(entries) {
  const byApp = new Map(APPS.map((app) => [app, new Map()]));
  const rank = { shared: 0, group: 1, app: 2 };
  const winner = new Map(APPS.map((app) => [app, new Map()]));

  for (const { key, value } of entries) {
    const { scope, targets, key: canonical } = classify(key);
    if (scope === "root") continue;
    for (const app of targets) {
      const seen = winner.get(app).get(canonical);
      if (seen !== undefined && seen > rank[scope]) continue;
      winner.get(app).set(canonical, rank[scope]);
      byApp.get(app).set(canonical, value);
    }
  }

  return byApp;
}

function render(source, values) {
  const body = [...values].map(([key, value]) => `${key}=${value}`).join("\n");
  return `${header(source)}${body}\n`;
}

/** True when the file on disk was written by this script rather than by hand. */
function isGenerated(path) {
  return existsSync(path) && readFileSync(path, "utf8").includes(MARKER);
}

function syncOne(sourceName, { check }) {
  const sourcePath = join(REPO_ROOT, sourceName);
  if (!existsSync(sourcePath)) return { skipped: true, stale: [], written: [] };

  const entries = parseEnv(readFileSync(sourcePath, "utf8"));
  const byApp = distribute(entries);
  const stale = [];
  const written = [];

  // Refuse to run against a root file that predates this scheme. `pnpm build`
  // and `pnpm dev` both call the sync, so without this check the first build
  // after pulling MDRS-25 would silently replace six hand-written .env files
  // with whatever the old docker-compose-only root .env happened to hold. The
  // .bak copies make that recoverable, not harmless.
  //
  // The signal is a root file with no prefixed key at all sitting next to app
  // files this script did not write: nobody who has adopted the scheme has a
  // root file without a single WEB__/API__/APP__ key.
  if (!check) {
    const handWritten = APPS.filter((app) => {
      const path = join(REPO_ROOT, "apps", app, sourceName);
      return existsSync(path) && !isGenerated(path);
    });

    if (
      handWritten.length > 0 &&
      !entries.some(({ key }) => key.includes("__"))
    ) {
      throw new Error(
        `${sourceName} taşınmamış görünüyor: içinde tek bir önekli anahtar yok, ` +
          `ama şu app'lerde elle yazılmış dosyalar duruyor: ${handWritten.join(", ")}.\n` +
          `Üzerlerine yazmadan önce root dosyayı onlardan kurun:\n\n` +
          `  pnpm env:collect > ${sourceName}\n\n` +
          `Gözden geçirip tekrar çalıştırın.`
      );
    }
  }

  for (const app of APPS) {
    const targetPath = join(REPO_ROOT, "apps", app, sourceName);
    const next = render(sourceName, byApp.get(app));
    const current = existsSync(targetPath)
      ? readFileSync(targetPath, "utf8")
      : null;

    if (current === next) continue;
    if (check) {
      stale.push(relative(REPO_ROOT, targetPath));
      continue;
    }

    // A file this script did not write holds values nobody else has a copy of.
    // Real .env files are git-ignored, so an overwrite without a backup is
    // unrecoverable — the exact failure MDRS-25 lists under Risk.
    if (current !== null && !isGenerated(targetPath)) {
      writeFileSync(`${targetPath}.bak`, current);
      written.push(`${relative(REPO_ROOT, targetPath)}.bak (önceki içerik)`);
    }

    writeFileSync(targetPath, next);
    written.push(relative(REPO_ROOT, targetPath));
  }

  return { skipped: false, stale, written };
}

/**
 * Assemble a root file from whatever the per-app files hold today. Used once,
 * to move an existing machine onto the scheme without retyping secrets: keys
 * that agree everywhere come out unprefixed, the rest come out prefixed.
 */
function collect() {
  const seen = new Map();

  for (const app of APPS) {
    const path = join(REPO_ROOT, "apps", app, ".env");
    if (!existsSync(path)) continue;
    for (const { key, value } of parseEnv(readFileSync(path, "utf8"))) {
      if (!seen.has(key)) seen.set(key, new Map());
      seen.get(key).set(app, value);
    }
  }

  const shared = [];
  const grouped = [];
  const perApp = [];

  // The only value worth having in a collected file is the deduplication, so
  // hoist as far as each key will go: agreed across both groups -> shared,
  // agreed within one group -> that group, and only the genuine disagreements
  // stay per app. A key that disagrees is exactly the drift MDRS-25 is about,
  // so it surfaces as several APP__ lines sitting next to each other.
  const agreed = (apps) => {
    const values = new Set(apps.map(([, value]) => value));
    return values.size === 1 ? [...values][0] : null;
  };

  for (const [key, byApp] of seen) {
    const present = [...byApp];
    const web = present.filter(([app]) => WEB_APPS.includes(app));
    const api = present.filter(([app]) => API_APPS.includes(app));

    const everywhere = agreed(present);
    if (everywhere !== null && web.length > 0 && api.length > 0) {
      shared.push(`${key}=${everywhere}`);
      continue;
    }

    for (const [group, members] of [
      ["WEB", web],
      ["API", api],
    ]) {
      if (members.length === 0) continue;
      const value = members.length > 1 ? agreed(members) : null;
      if (value !== null) grouped.push(`${group}__${key}=${value}`);
      else
        for (const [app, v] of members)
          perApp.push(`${app.toUpperCase()}__${key}=${v}`);
    }
  }

  return [
    "# Assembled from the existing apps/*/.env files by `pnpm env:collect`.",
    "# Review before adopting: a key that only happens to agree today is hoisted",
    "# to shared or to a group, and every key that disagrees is left per app —",
    "# each of those is a drift to resolve or to justify with a comment.",
    "",
    "# --- shared ---",
    ...shared.sort(),
    "",
    "# --- per group ---",
    ...grouped.sort(),
    "",
    "# --- per app ---",
    ...perApp.sort(),
    "",
  ].join("\n");
}

const args = new Set(process.argv.slice(2));

if (args.has("--collect")) {
  process.stdout.write(collect());
  process.exit(0);
}

const check = args.has("--check");
const sources = args.has("--examples")
  ? [".env.example"]
  : [".env.example", ".env"];
let results;
try {
  results = sources.map((name) => [name, syncOne(name, { check })]);
} catch (error) {
  // A stack trace here is noise: every throw in this script is a message
  // written for whoever ran it, and this runs inside `pnpm build`.
  console.error(`env: ${error.message}`);
  process.exit(1);
}

if (check) {
  const stale = results.flatMap(([, r]) => r.stale);
  if (stale.length > 0) {
    console.error("Bu dosyalar kaynağıyla uyumsuz:\n");
    for (const path of stale) console.error(`  ${path}`);
    console.error("\n`pnpm env:sync` çalıştırıp sonucu commit edin.");
    process.exit(1);
  }
  console.log("env: üretilen dosyalar kaynakla uyumlu.");
  process.exit(0);
}

for (const [name, result] of results) {
  if (result.skipped) {
    console.log(`env: ${name} yok, atlandı.`);
    continue;
  }
  if (result.written.length === 0) {
    console.log(`env: ${name} → değişiklik yok.`);
    continue;
  }
  console.log(`env: ${name} →`);
  for (const path of result.written) console.log(`  ${path}`);
}
