#!/usr/bin/env node
// Regenerates src/css/*.css, src/tokens.ts and src/tailwind-preset.js from tokens/tokens.json.
// Zero dependencies. Run: node tools/build-tokens.mjs  (or: nx build design-system)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const tokens = JSON.parse(readFileSync(resolve(root, "tokens/tokens.json"), "utf8"));
const GROUP_FILES = {
  color: "colors.css", font: "fonts-vars.css", fontSize: "typography.css",
  fontWeight: "typography.css", letterSpacing: "typography.css", lineHeight: "typography.css",
  space: "spacing.css", layout: "spacing.css", radius: "radii.css",
  shadow: "elevation.css", scrim: "elevation.css",
  duration: "motion.css", easing: "motion.css", transition: "motion.css"
};
function flatten(node, path = [], out = []) {
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith("$")) continue;
    if (v && typeof v === "object" && "$value" in v) out.push({ path: [...path, k], ...v });
    else if (v && typeof v === "object") flatten(v, [...path, k], out);
  }
  return out;
}
const camel = (parts) =>
  parts.map((p, i) => {
    const s = p.replace(/-(\w)/g, (_, c) => c.toUpperCase());
    return i === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1);
  }).join("");
function toCssFiles(tokens) {
  const byFile = {};
  for (const t of flatten(tokens)) {
    const file = GROUP_FILES[t.path[0]] || "misc.css";
    (byFile[file] ||= []).push(t);
  }
  const files = {};
  for (const [file, list] of Object.entries(byFile)) {
    const lines = list.map(t =>
      "  " + t.$name + ": " + t.$value + ";" + (t.$description ? " /* " + t.$description + " */" : "")
    );
    files[file] = ":root {\n" + lines.join("\n") + "\n}\n";
  }
  return files;
}
function toTs(tokens) {
  const list = flatten(tokens);
  const entries = list.map(t => "  " + camel(t.path) + ': "' + String(t.$value).replace(/"/g, '\\"') + '",');
  const vars = list.map(t => "  " + camel(t.path) + ': "var(' + t.$name + ')",');
  return [
    "// GENERATED by tools/build-tokens.mjs — do not edit.",
    "export const tokens = {", ...entries, "} as const;",
    "",
    "/** Same keys, but as var() references — prefer these in components. */",
    "export const cssVar = {", ...vars, "} as const;",
    "",
    "export type TokenName = keyof typeof tokens;",
    ""
  ].join("\n");
}
function toTailwindPreset(tokens) {
  const pick = (root) => Object.fromEntries(
    flatten(tokens).filter(t => t.path[0] === root)
      .map(t => [t.path.slice(1).join("-") || t.path[0], "var(" + t.$name + ")"])
  );
  const preset = {
    theme: {
      extend: {
        colors: pick("color"),
        spacing: { ...pick("space"), ...pick("layout") },
        borderRadius: pick("radius"),
        fontSize: pick("fontSize"),
        fontWeight: pick("fontWeight"),
        letterSpacing: pick("letterSpacing"),
        lineHeight: pick("lineHeight"),
        boxShadow: pick("shadow"),
        fontFamily: { ui: "var(--font-ui)", arabic: "var(--font-arabic)", mono: "var(--font-mono)" },
        transitionDuration: pick("duration"),
        transitionProperty: pick("transition")
      }
    }
  };
  return "// GENERATED by tools/build-tokens.mjs — do not edit.\nmodule.exports = " +
    JSON.stringify(preset, null, 2) + ";\n";
}

const write = (p, c) => { mkdirSync(dirname(p), { recursive: true }); writeFileSync(p, c); console.log("  ✓", p.replace(root + "/", "")); };

console.log("building design tokens…");
for (const [name, css] of Object.entries(toCssFiles(tokens))) write(resolve(root, "src/css", name), css);
write(resolve(root, "src/tokens.ts"), toTs(tokens));
write(resolve(root, "src/tailwind-preset.js"), toTailwindPreset(tokens));
console.log("done.");
