#!/usr/bin/env node
// Generates, from a design system's assets/icons.svg (the one glyph source,
// MDS-ICON-01), every copy of it the system keeps:
//   components/Icon.d.ts  the `name` union line of IconProps;
//   components/Icon.jsx   the block between the BEGIN/END generated markers:
//                         the path tables, the mirrored set and `iconNames`;
//   components.css, medrese.css
//                         one "Glyph masks (generated)" section: a mask-image
//                         for each request in the masks file for that layer.
//                         A layer file that does not exist is skipped.
// A mask request is {layer, selector, glyph}; the rule sets only the image, and
// the requesting component's own section sizes and colours the element.
// --check writes nothing and fails when a copy differs from the sprite, or a
// requested glyph is not in it.
import fs from "node:fs";
import path from "node:path";
import { fromRoot, parseArgs, readJson, usageError } from "./lib.mjs";

const USAGE =
  "node tools/design-system/icons.mjs --dir <design-system-dir> [--masks <file>] [--check]";
const VALUE_FLAGS = new Set(["--dir", "--masks"]);
const raw = process.argv.slice(2);
const argv = [];
for (let i = 0; i < raw.length; i++) {
  if (VALUE_FLAGS.has(raw[i]) && i + 1 < raw.length) {
    argv.push(`${raw[i]}=${raw[++i]}`);
  } else argv.push(raw[i]);
}
const { args, flags } = parseArgs(USAGE, ["dir", "masks", "check"], argv);
if (args.length) usageError(USAGE, `unexpected argument: ${args[0]}`);
if (typeof flags.dir !== "string") usageError(USAGE, "--dir is required");
if (flags.masks === true) usageError(USAGE, "--masks needs a file");

const dir = fromRoot(flags.dir);
const masksPath = fromRoot(
  flags.masks ?? "tools/design-system/icon-masks.json"
);
const spritePath = path.join(dir, "assets/icons.svg");
if (!fs.existsSync(spritePath)) usageError(USAGE, `no sprite at ${spritePath}`);

const LAYERS = ["components.css", "medrese.css"];
const SECTION = "Glyph masks (generated)";
const BEGIN =
  "// BEGIN generated by tools/design-system/icons.mjs from assets/icons.svg; never edit by hand";
const END = "// END generated";

const errors = [];
const fail = (m) => errors.push(m);
function bail() {
  if (!errors.length) return;
  for (const e of errors) console.error(`✖ ${e}`);
  process.exit(1);
}

// ------------------------------------------------------------------ sprite
// A symbol is `<symbol id viewBox="0 0 256 256" data-glyph [data-directional]
// [data-weight="fill"]>` holding only `<path d="…"/>` elements. An id ending
// in -fill is the filled twin of the id without it.
function readSprite(file) {
  const src = fs.readFileSync(file, "utf8").replace(/<!--[\s\S]*?-->/g, "");
  const symbols = new Map();
  for (const m of src.matchAll(/<symbol\b([^>]*)>([\s\S]*?)<\/symbol>/g)) {
    const attrs = Object.fromEntries(
      [...m[1].matchAll(/([\w-]+)="([^"]*)"/g)].map((a) => [a[1], a[2]])
    );
    const { id } = attrs;
    if (!id || !/^[a-z][A-Za-z0-9]*(-fill)?$/.test(id)) {
      fail(`symbol id ${JSON.stringify(id)}: expected a camelCase name`);
      continue;
    }
    if (symbols.has(id)) fail(`symbol ${id} appears twice`);
    if (attrs.viewBox !== "0 0 256 256") {
      fail(`symbol ${id}: viewBox must be "0 0 256 256"`);
    }
    const paths = [...m[2].matchAll(/<path d="([^"]+)"\s*\/>/g)].map(
      (p) => p[1]
    );
    const rest = m[2].replace(/<path d="[^"]+"\s*\/>/g, "").trim();
    if (!paths.length || rest) {
      fail(`symbol ${id}: only <path d="…"/> children are allowed`);
    }
    symbols.set(id, {
      paths,
      directional: attrs["data-directional"] === "true",
    });
  }
  for (const id of symbols.keys()) {
    if (id.endsWith("-fill") && !symbols.has(id.slice(0, -5))) {
      fail(`symbol ${id} has no regular twin ${id.slice(0, -5)}`);
    }
  }
  if (!symbols.size) fail(`${file}: no <symbol> found`);
  return symbols;
}

const symbols = readSprite(spritePath);
bail();
const names = [...symbols.keys()].filter((id) => !id.endsWith("-fill"));
const filled = names.filter((n) => symbols.has(`${n}-fill`));
const mirrored = names.filter((n) => symbols.get(n).directional);

// ------------------------------------------------------------ generated text
const quote = (s) => `'${s}'`;
const table = (keys, idOf) =>
  keys
    .map(
      (k) => `  ${k}: [${symbols.get(idOf(k)).paths.map(quote).join(", ")}],`
    )
    .join("\n");

const jsxBlock = `${BEGIN}
const glyphs = {
${table(names, (n) => n)}
};
const fillGlyphs = {
${table(filled, (n) => `${n}-fill`)}
};
const mirrored = new Set([${mirrored.map(quote).join(", ")}]);
export const iconNames = Object.keys(glyphs);
${END}`;

const unionLine = `  name: ${names.map(quote).join(" | ")};`;

// The class layers' section header: `/* ---- Title */`, as wide as theirs.
const header = (title) =>
  `/* ${"-".repeat(Math.max(3, 70 - title.length))} ${title} */`;
const HEADER_RE = /^\/\* -{3,} (.+?) \*\/\s*$/;

const encode = (svg) =>
  svg
    .replace(/%/g, "%25")
    .replace(/</g, "%3C")
    .replace(/>/g, "%3E")
    .replace(/#/g, "%23")
    .replace(/"/g, "%22");
function maskUrl(glyph) {
  const body = symbols
    .get(glyph)
    .paths.map((d) => `<path d='${d}'/>`)
    .join("");
  return `url("data:image/svg+xml,${encode(`<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 256 256'>${body}</svg>`)}")`;
}

function maskSection(requests) {
  const rules = [...requests]
    .sort((a, b) =>
      a.selector < b.selector ? -1 : a.selector > b.selector ? 1 : 0
    )
    .map((r) => {
      const url = maskUrl(r.glyph);
      return `${r.selector} { -webkit-mask-image: ${url}; mask-image: ${url}; }`;
    });
  return [
    header(SECTION),
    "/* Written by tools/design-system/icons.mjs from assets/icons.svg and the masks",
    "   file (tools/design-system/icon-masks.json); never edit it by hand. Each rule",
    "   sets only the glyph: the requesting component's section sizes and colours it. */",
    ...rules,
  ].join("\n");
}

// Replaces the section titled SECTION (header line to the next header or the
// end), appends it when absent, removes it when `section` is null.
function withSection(css, section) {
  const lines = css.split("\n");
  const start = lines.findIndex((l) => l.match(HEADER_RE)?.[1] === SECTION);
  let text;
  if (start < 0) {
    if (!section) return css;
    const kept = css.replace(/\n*$/, "");
    text = kept ? `${kept}\n\n${section}\n` : `${section}\n`;
  } else {
    let end = lines.findIndex((l, i) => i > start && HEADER_RE.test(l));
    if (end < 0) end = lines.length;
    const before = lines.slice(0, start).join("\n").replace(/\n*$/, "");
    const after = lines.slice(end).join("\n").replace(/^\n*/, "");
    text = [before, section, after].filter(Boolean).join("\n\n");
    text = `${text.replace(/\n*$/, "")}\n`;
  }
  return text;
}

// ------------------------------------------------------------------- masks
function readMasks(file) {
  if (!fs.existsSync(file)) usageError(USAGE, `no masks file at ${file}`);
  let data;
  try {
    data = readJson(file);
  } catch (e) {
    usageError(USAGE, `${file}: ${e.message}`);
  }
  if (!Array.isArray(data?.masks)) {
    usageError(USAGE, `${file}: expected {"masks": [...]}`);
  }
  const seen = new Set();
  for (const [i, m] of data.masks.entries()) {
    const at = `${path.basename(file)} masks[${i}]`;
    if (!LAYERS.includes(m?.layer)) {
      fail(`${at}: layer must be one of ${LAYERS.join(", ")}`);
    }
    if (
      typeof m?.selector !== "string" ||
      !m.selector.trim() ||
      /[{};]/.test(m.selector)
    ) {
      fail(`${at}: selector must be a non-empty selector`);
    }
    if (!symbols.has(m?.glyph)) {
      fail(
        `${at}: glyph ${JSON.stringify(m?.glyph)} is not in assets/icons.svg`
      );
    }
    const key = `${m?.layer} ${m?.selector}`;
    if (seen.has(key)) fail(`${at}: ${key} is requested twice`);
    seen.add(key);
  }
  return data.masks;
}

const masks = readMasks(masksPath);
bail();

// ------------------------------------------------------------------ outputs
const outputs = [];
const skipped = [];

const dtsPath = path.join(dir, "components/Icon.d.ts");
const jsxPath = path.join(dir, "components/Icon.jsx");
for (const p of [dtsPath, jsxPath]) {
  if (!fs.existsSync(p)) fail(`no ${path.relative(dir, p)} in ${dir}`);
}
bail();

const dts = fs.readFileSync(dtsPath, "utf8");
const iface = dts.search(/export interface IconProps\b/);
const nameLine = /^[ \t]*name: '.*;[ \t]*$/m;
const nameAt = iface < 0 ? -1 : dts.slice(iface).search(nameLine);
if (nameAt < 0) {
  fail("components/Icon.d.ts: no `name: '…';` line in IconProps");
} else {
  outputs.push({
    file: dtsPath,
    current: dts,
    next: dts.slice(0, iface) + dts.slice(iface).replace(nameLine, unionLine),
  });
}

const jsx = fs.readFileSync(jsxPath, "utf8");
const b = jsx.indexOf(BEGIN);
const e = b < 0 ? -1 : jsx.indexOf(END, b);
if (e < 0) {
  fail("components/Icon.jsx: no BEGIN/END generated block");
} else {
  outputs.push({
    file: jsxPath,
    current: jsx,
    next: jsx.slice(0, b) + jsxBlock + jsx.slice(e + END.length),
  });
}

for (const layer of LAYERS) {
  const file = path.join(dir, layer);
  const requests = masks.filter((m) => m.layer === layer);
  if (!fs.existsSync(file)) {
    if (requests.length) skipped.push({ layer, count: requests.length });
    continue;
  }
  const css = fs.readFileSync(file, "utf8");
  const section = requests.length ? maskSection(requests) : null;
  outputs.push({ file, current: css, next: withSection(css, section) });
}
bail();

const summary = `${names.length} names, ${filled.length} filled, ${mirrored.length} mirrored, ${masks.length} mask request(s)`;
const stale = outputs.filter((o) => o.current !== o.next);
if (flags.check) {
  for (const o of stale) {
    console.error(
      `✖ ${path.relative(dir, o.file)} differs from assets/icons.svg`
    );
  }
  for (const s of skipped) {
    console.error(
      `✖ ${s.count} mask(s) requested for ${s.layer}, which does not exist`
    );
  }
  if (stale.length || skipped.length) process.exit(1);
  console.log(`✔ every generated copy matches assets/icons.svg (${summary})`);
  process.exit(0);
}
for (const o of stale) {
  fs.writeFileSync(o.file, o.next);
  console.log(`wrote ${path.relative(dir, o.file)}`);
}
for (const s of skipped) {
  console.warn(`skipped ${s.count} mask(s) for ${s.layer}: no such file`);
}
console.log(`${stale.length ? "updated" : "unchanged"} (${summary})`);
