#!/usr/bin/env node
// Copies the unified design system into the two workspace packages the apps
// build from (MDRS-151). Nothing in apps/ or libs/ may import design-system/:
// .dockerignore leaves it out of every image, so such an import passes every
// local gate and fails only inside the image build. This script is the one
// path from the system to the code, and `--check` proves the copies current.
//
//   libs/tokens/medaris.css          every tokens/*.css that styles.css imports,
//                                    in its order, except fonts.css
//   libs/tokens/medaris-fonts.js     the two Google Fonts URLs from fonts.css,
//                                    for a <link> in the document head
//   libs/ui/src/styles/mds/*.css     components.css and medrese.css, byte for byte
//   libs/ui/src/mds/glyphs.ts        the generated block of components/Icon.jsx
//
// fonts.css is left out of medaris.css on purpose: its @import url() lines
// would land after other rules once Tailwind inlines the file, where a browser
// ignores them. The system's readme asks for a <link> with preconnect in
// production, which is what medaris-fonts.js feeds.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { DEFAULT_DIR, fromRoot, parseArgs, repoRoot } from "./lib.mjs";

const USAGE =
  "usage: node tools/design-system/sync-libs.mjs [--dir=<design-system-dir>] [--check]";
const { flags } = parseArgs(USAGE, ["dir", "check"]);
const dir = fromRoot(flags.dir ?? DEFAULT_DIR);
const check = Boolean(flags.check);

const read = (p) => readFileSync(join(dir, p), "utf8");
const source = relative(repoRoot, dir);
const header = (what) =>
  `/* Generated by tools/design-system/sync-libs.mjs from ${source}/${what}; never edit by hand. */\n`;

// styles.css is the system's own statement of what loads, and in which order.
const order = [
  ...read("styles.css").matchAll(/@import url\("([^"]+)"\);/g),
].map((m) => m[1]);
if (!order.includes("components.css") || !order.includes("tokens/fonts.css")) {
  throw new Error(
    `${source}/styles.css no longer imports what this script expects: ${order.join(", ")}`
  );
}

const tokenFiles = order.filter(
  (p) => p.startsWith("tokens/") && p !== "tokens/fonts.css"
);
const classFiles = order.filter((p) => !p.startsWith("tokens/"));

const fonts = read("tokens/fonts.css");
const fontUrls = [...fonts.matchAll(/@import url\("([^"]+)"\);/g)].map(
  (m) => m[1]
);
// fonts.css must hold nothing but its comment and the @import lines, or
// leaving it out of medaris.css would drop a token.
const fontsRest = fonts
  .replace(/\/\*[\s\S]*?\*\//g, "")
  .replace(/@import url\("[^"]+"\);/g, "")
  .trim();
if (fontUrls.length !== 2 || fontsRest !== "") {
  throw new Error(
    `${source}/tokens/fonts.css changed shape: ${fontUrls.length} @import lines, extra content: ${JSON.stringify(fontsRest.slice(0, 80))}`
  );
}
const [textFonts, quranFonts] = fontUrls;
if (
  !textFonts.includes("family=Instrument+Sans") ||
  !quranFonts.includes("family=Scheherazade+New")
) {
  throw new Error(
    `${source}/tokens/fonts.css: the two @import lines are not the text faces and the Qur'an face, in that order`
  );
}

const icon = read("components/Icon.jsx");
const block = icon.match(
  /\/\/ BEGIN generated[^\n]*\n([\s\S]*?)\n\/\/ END generated/
);
if (!block)
  throw new Error(`${source}/components/Icon.jsx has no generated block`);
const glyphSource = block[1]
  .replace(/^const glyphs = \{/m, "export const glyphs = {")
  .replace(
    /^const fillGlyphs = \{/m,
    "export const fillGlyphs: Partial<Record<IconName, readonly string[]>> = {"
  )
  .replace(
    /^const mirrored = new Set\(/m,
    "export const mirrored: ReadonlySet<string> = new Set("
  )
  .replace(
    /^export const iconNames = Object\.keys\(glyphs\);$/m,
    "export const iconNames = Object.keys(glyphs) as IconName[];"
  );
if (
  !/export const glyphs = \{/.test(glyphSource) ||
  !/as IconName\[\]/.test(glyphSource)
) {
  throw new Error(
    `${source}/components/Icon.jsx: the generated block changed shape`
  );
}

const outputs = new Map([
  [
    "libs/tokens/medaris.css",
    header("tokens/*.css") +
      tokenFiles
        .map((p) => `/* ---- ${p} ---- */\n${read(p).replace(/\n*$/, "\n")}`)
        .join("\n"),
  ],
  [
    "libs/tokens/medaris-fonts.js",
    `// Generated by tools/design-system/sync-libs.mjs from ${source}/tokens/fonts.css; never edit by hand.\n` +
      "// The text faces (Instrument Sans, Literata, Noto Naskh Arabic, Atkinson Hyperlegible Mono), on every page.\n" +
      `export const textFontsHref = ${JSON.stringify(textFonts)};\n` +
      "// Scheherazade New, only on a page that shows Qur'anic text.\n" +
      `export const quranFontHref = ${JSON.stringify(quranFonts)};\n`,
  ],
  ...classFiles.map((p) => [`libs/ui/src/styles/mds/${p}`, read(p)]),
  [
    "libs/ui/src/mds/glyphs.ts",
    `// Generated by tools/design-system/sync-libs.mjs from ${source}/components/Icon.jsx; never edit by hand.\n` +
      `${glyphSource}\n` +
      "export type IconName = keyof typeof glyphs;\n",
  ],
]);

// Read and treat ENOENT as "absent" rather than asking existsSync first: a
// check-then-use pair is the file-system race CodeQL flags (js/file-system-race).
function readIfPresent(target) {
  try {
    return readFileSync(target, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

let stale = 0;
for (const [path, content] of outputs) {
  const target = fromRoot(path);
  const current = readIfPresent(target);
  if (current === content) continue;
  if (check) {
    console.error(`stale: ${path}`);
    stale++;
    continue;
  }
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, content);
  console.log(`wrote ${path}`);
}

if (check) {
  if (stale) {
    console.error(
      `${stale} file(s) differ from ${source}; run node tools/design-system/sync-libs.mjs`
    );
    process.exit(1);
  }
  console.log(`${outputs.size} files match ${source}`);
}
