#!/usr/bin/env node
// Generates pr95-value-bridge.css (SPEC-D3-17 option b) from pr95-map.json and
// a design system's generated manifest: every #95 token whose map targets
// (`to` plus every `byProperty` value) resolve to ONE value in that manifest is
// declared with that value, as a literal, because the MDRS-127 project that
// loads the bridge has no canonical tokens. Property-dependent and dropped
// names, and names whose entry `inherits` an open decision (their targets are
// pairs that wait on it), are left out and listed in the file's header.
//
// Values are the manifest's, i.e. each token's last declaration; regenerate
// the manifest with regen.mjs before running this.
import fs from "node:fs";
import path from "node:path";
import {
  fromRoot,
  manifestOf,
  parseArgs,
  readJson,
  resolver,
  usageError,
} from "./lib.mjs";

const USAGE =
  "node tools/design-system/value-bridge.mjs <pr95-map.json> <design-system-dir> <out.css> [--check]";
const { args, flags } = parseArgs(USAGE, ["check"]);
if (args.length !== 3) {
  usageError(USAGE, "expected <pr95-map.json> <design-system-dir> <out.css>");
}
const [mapPath, dsDir, outPath] = args.map(fromRoot);

const map = readJson(mapPath);
const values = new Map(manifestOf(dsDir).tokens.map((t) => [t.name, t.value]));
const resolve = resolver(values);

const single = [];
const multi = [];
const dropped = [];
const held = [];
const errors = [];
for (const [name, entry] of Object.entries(map.tokens)) {
  if (entry.inherits) {
    held.push(`${name} (${entry.inherits})`);
    continue;
  }
  const targets = new Set(
    [entry.to, ...Object.values(entry.byProperty ?? {})].filter(
      (t) => typeof t === "string" && t.startsWith("--")
    )
  );
  if (!targets.size) {
    dropped.push(name);
    continue;
  }
  const unknown = [...targets].filter((t) => !values.has(t));
  if (unknown.length) {
    errors.push(`${name} → ${unknown.join(", ")} (not in the manifest)`);
    continue;
  }
  const resolved = new Set(
    [...targets].map((t) => resolve(`var(${t})`).trim())
  );
  if (resolved.size > 1) multi.push(name);
  else {
    const [value] = resolved;
    if (value.includes("var(")) errors.push(`${name} → ${value} (unresolved)`);
    else single.push([name, value]);
  }
}
if (errors.length) {
  for (const e of errors) console.error(`✖ ${e}`);
  process.exit(1);
}

const fontsCss = fs.readFileSync(path.join(dsDir, "tokens/fonts.css"), "utf8");
const fontsImport = fontsCss.match(/@import url\([^)]*\);/)?.[0];
if (!fontsImport) {
  console.error(
    `✖ no @import url(…) in ${path.join(dsDir, "tokens/fonts.css")}`
  );
  process.exit(1);
}

const css = `/* GENERATED by tools/design-system/value-bridge.mjs from pr95-map.json (SPEC-D3-17 option b). Do not edit.
   Load AFTER the #95 CSS in the MDRS-127 project only. It gives ${single.length} #95 token names their canonical values,
   so screens drawn on #95 names take the unified look without a rename. Never loaded by the unified system.
   Not bridged (rename after launch via pr95-map.json): property-dependent ${multi.join(", ")}; dropped ${dropped.join(", ")};
   waiting on an open decision ${held.join(", ")}.
   Removal condition: delete when the MDRS-127 screens are ported by pr95-map.json. */
${fontsImport}
:root {
${single.map(([n, v]) => `  ${n}: ${v};`).join("\n")}
}
`;

const summary = `bridged ${single.length}, property-dependent ${multi.length}, dropped ${dropped.length}, waiting on an open decision ${held.length}`;
if (flags.check) {
  const current = fs.existsSync(outPath)
    ? fs.readFileSync(outPath, "utf8")
    : null;
  if (current === css) {
    console.log(`✔ ${outPath} is up to date (${summary})`);
    process.exit(0);
  }
  console.error(
    `✖ ${outPath} ${current === null ? "does not exist" : "differs from what the map and manifest generate"} (${summary})`
  );
  process.exit(1);
}
fs.writeFileSync(outPath, css);
console.log(`wrote ${outPath} (${summary})`);
